<?php

/**
 * @file
 * Contains formazing.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 * @return string
 */
function formazing_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the formazing module.
    case 'help.page.formazing':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create amazing forms in interface and can be linked to a webservice') . '</p>';
      return $output;

    default:
  }
}

/**
 * When removing a custom form, remove also linked fields
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function formazing_entity_delete(\Drupal\Core\Entity\EntityInterface $entity) {
    if (!$entity instanceof \Drupal\formazing\Entity\FormazingEntity) {
        return;
    }
    
    $id = $entity->id();
    $field_type = 'field_formazing_entity';
    $results = \Drupal::entityQuery($field_type)
        ->condition('formazing_id', $id)
        ->execute();
    
    
    $storage_handler = \Drupal::entityTypeManager()->getStorage($field_type);
    $entities = $storage_handler->loadMultiple($results);
    $storage_handler->delete($entities);
}
