<?php

/**
 * @file
 * Contains formazing.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function formazing_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the formazing module.
    case 'help.page.formazing':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Create amazing forms in interface and can be linked to a webservice') . '</p>';
      return $output;

    default:
  }
}
